// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Relationships.Infrastructure.Persistence.Database;

namespace Relationships.Infrastructure.Persistence.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Relationships.Domain.Entities.Relationship", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<string>("RelationshipTemplateId")
                        .HasColumnType("char(20)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("From");

                    b.HasIndex("RelationshipTemplateId");

                    b.HasIndex("Status");

                    b.HasIndex("To");

                    b.ToTable("Relationships");
                });

            modelBuilder.Entity("Relationships.Domain.Entities.RelationshipChange", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelationshipId")
                        .IsRequired()
                        .HasColumnType("char(20)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("RelationshipId");

                    b.HasIndex("Status");

                    b.HasIndex("Type");

                    b.ToTable("RelationshipChanges");

                    b.HasDiscriminator<string>("Discriminator").HasValue("RelationshipChange");
                });

            modelBuilder.Entity("Relationships.Domain.Entities.RelationshipChangeRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("Req_CreatedAt");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("Req_CreatedBy");

                    b.Property<string>("CreatedByDevice")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Req_CreatedByDevice");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedByDevice");

                    b.ToTable("RelationshipChanges");
                });

            modelBuilder.Entity("Relationships.Domain.Entities.RelationshipChangeResponse", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("Res_CreatedAt");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("Res_CreatedBy");

                    b.Property<string>("CreatedByDevice")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Res_CreatedByDevice");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedByDevice");

                    b.ToTable("RelationshipChanges");
                });

            modelBuilder.Entity("Relationships.Domain.Entities.RelationshipTemplate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CreatedByDevice")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MaxNumberOfRelationships")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("RelationshipTemplates");
                });

            modelBuilder.Entity("Relationships.Domain.Entities.RelationshipCreationChange", b =>
                {
                    b.HasBaseType("Relationships.Domain.Entities.RelationshipChange");

                    b.ToTable("RelationshipChanges");

                    b.HasDiscriminator().HasValue("RelationshipCreationChange");
                });

            modelBuilder.Entity("Relationships.Domain.Entities.RelationshipTerminationChange", b =>
                {
                    b.HasBaseType("Relationships.Domain.Entities.RelationshipChange");

                    b.ToTable("RelationshipChanges");

                    b.HasDiscriminator().HasValue("RelationshipTerminationChange");
                });

            modelBuilder.Entity("Relationships.Domain.Entities.Relationship", b =>
                {
                    b.HasOne("Relationships.Domain.Entities.RelationshipTemplate", "RelationshipTemplate")
                        .WithMany("Relationships")
                        .HasForeignKey("RelationshipTemplateId");

                    b.Navigation("RelationshipTemplate");
                });

            modelBuilder.Entity("Relationships.Domain.Entities.RelationshipChange", b =>
                {
                    b.HasOne("Relationships.Domain.Entities.Relationship", "Relationship")
                        .WithMany("Changes")
                        .HasForeignKey("RelationshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Relationship");
                });

            modelBuilder.Entity("Relationships.Domain.Entities.RelationshipChangeRequest", b =>
                {
                    b.HasOne("Relationships.Domain.Entities.RelationshipChange", null)
                        .WithOne("Request")
                        .HasForeignKey("Relationships.Domain.Entities.RelationshipChangeRequest", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Relationships.Domain.Entities.RelationshipChangeResponse", b =>
                {
                    b.HasOne("Relationships.Domain.Entities.RelationshipChange", null)
                        .WithOne("Response")
                        .HasForeignKey("Relationships.Domain.Entities.RelationshipChangeResponse", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Relationships.Domain.Entities.Relationship", b =>
                {
                    b.Navigation("Changes");
                });

            modelBuilder.Entity("Relationships.Domain.Entities.RelationshipChange", b =>
                {
                    b.Navigation("Request")
                        .IsRequired();

                    b.Navigation("Response");
                });

            modelBuilder.Entity("Relationships.Domain.Entities.RelationshipTemplate", b =>
                {
                    b.Navigation("Relationships");
                });
#pragma warning restore 612, 618
        }
    }
}
